---
- hosts: default
  gather_facts: True
  user: ec2-user
  sudo: True
#- hosts: tag_jenkins_master
  tasks:

   - name: install Java_1.7
     yum:
        name: java-1.7.0
        state: absent

   - name: install Java_1.8
     yum:
        name: java-1.8.0
        state: present

   - name: copying repo
     get_url:
        url: http://pkg.jenkins-ci.org/redhat/jenkins.repo
        dest: /etc/yum.repos.d/

   - name: add the repository keys
     rpm_key: 
        key: https://jenkins-ci.org/redhat/jenkins-ci.org.key
        state: present

   - name: install jenkins
     yum:
        name: "{{item}}"
        state: present
     with_items:
        - jenkins
        - git

   - name: Enabled jenkins Master Service
     service:
       name: jenkins
       #state: stopped
       enabled: yes

   - name: Add user Public Key
     copy:
       src: "/root/glp-task/jenkins-master-ami/files/id_rsa.pub"
       dest: "/root/.ssh/id_rsa.pub"
       mode: 0644

   - name: Add user Private Key
     copy:
       src: "/root/glp-task/jenkins-master-ami/files/id_rsa"
       dest: "/root/.ssh/id_rsa"
       mode: 0600

   - git:
       repo: ssh://git@bitbucket.pearson.com/glpin/glp-db-automation.git
       dest: /root/amit-git
       accept_hostkey: yes
       key_file: /root/.ssh/id_rsa

   - git:
       repo: ssh://git@bitbucket.pearson.com/glpin/glp-infra-packer.git
       dest: /root/amit-plug
       accept_hostkey: yes
       key_file: /root/.ssh/id_rsa

   - git:
       repo: ssh://git@bitbucket.pearson.com/glpin/glp-jenkins-config-devops.git
       dest: /root/amit-config
       accept_hostkey: yes
       key_file: /root/.ssh/id_rsa
