- include_vars: ../jenkins_master/defaults/my_var.yml

## Configure Jenkins master
- name: Stop jenkins Master Service
  service:
    name: jenkins
    state: stopped
  ignore_errors: yes

- name:  Checking jenkins master version
  shell: "rpm -q jenkins-{{jenkins_version}}"
  register: result1
  ignore_errors: yes

- name: Remove jenkins version
  yum:
    name: "jenkins"
    state: absent
  register: result2
  when:
        - result1.rc == 1
  #when: (result1.find('not installed') != -1)

- name: Remove previous jenkins home data
  file: 
    path: "/var/lib/jenkins"
    state: absent
  when: ( result1.rc == 1 )
#  when:
#        - result2.rc == 0

- name: Installing Jenkins Entered Veriosn
  yum:
    name: "jenkins-{{jenkins_version}}"
    state: present
  when: ( result1.rc == 1 )


- name: Assigning shell to jenkins user
  user:
    name: jenkins
    shell: /bin/bash

- file:
    path: "{{ jenkins_home }}/.ssh"
    mode: 0700
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory

- file:
    path: "{{ jenkins_home }}/plugins"
    mode: 0755
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory

- name: Add user Public Key
  copy: 
     src: "../jenkins_master/files/jenkins_id_rsa.pub"
     dest: "{{ jenkins_home }}/.ssh/id_rsa.pub"
     mode: 0644
     owner: "{{ username }}"
     group: "{{ username }}"
  when: ( result1.rc == 1 )

- name: Add user Private Key
  copy: 
     src: "../jenkins_master/files/jenkins_id_rsa"
     dest: "{{ jenkins_home }}/.ssh/id_rsa"
     mode: 0600
     owner: "{{ username }}"
     group: "{{ username }}"
  when: ( result1.rc == 1 )

- name: Adding Bitbucket Public Key
  copy: 
     src: "../jenkins_master/files/bitbucket_pub"
     dest: "{{ jenkins_home }}/.ssh/known_hosts"
     mode: 0644
     owner: "{{ username }}"
     group: "{{ username }}"
  when: ( result1.rc == 1 )


- name: git config user name
  shell: git config --global user.name "{{ git_name }}" executable=/bin/bash
  become: yes
  become_user: "{{ username }}"

- name: git config user email
  shell: git config --global user.email "{{ git_email }}" executable=/bin/bash
  become: yes
  become_user: "{{ username }}"

- name: Pull Jenkins Configuration from bitbuket
  git:
    repo: "{{ jenkins_bucket_url }}"
    dest: "{{ jenkins_bucket }}"
    accept_hostkey: yes
    #clone: no
    force: yes
  become: yes
  become_user: "{{ username }}"

### // Add plugin name here my_var.yml to install on jenkins // ###
- name: Get other plugins from net
  get_url: 
   url: "https://updates.jenkins-ci.org/latest/{{item}}"
   dest: "{{  jenkins_home }}/plugins"
  with_items: "{{ jenkins_plugins }}"

- name: copying jobs and plugin from repo to jenkins home
  #shell: "cp -frv {{ jenkins_bucket }}/* /var/lib/jenkins/ ; chown  jenkins.jenkins -R /var/lib/jenkins/"
  shell: "cp -fvr {{ jenkins_plugin_bucket }}/jenkins-plug/* {{  jenkins_home }}/plugins; cp -frv {{ jenkins_bucket }}/* /var/lib/jenkins/ ; chown  jenkins.jenkins -R /var/lib/jenkins/"

- name: Start and Enabled jenkins Master Service
  service:
    name: jenkins
    state: started
    enabled: yes
