- include_vars: ../jenkins_master/defaults/my_var.yml

- name: Copying Jenkins repo
  get_url:
     url: http://pkg.jenkins-ci.org/redhat/jenkins.repo
     dest: /etc/yum.repos.d/

- name: Adding the repository gpg keys
  rpm_key:
     key: https://jenkins-ci.org/redhat/jenkins-ci.org.key
     state: present

- name: Removing Old Java_1.7 version
  yum:
    name: java-1.7.0
    state: absent

- name: Installing Jenkins Entered Veriosn and other packages
  yum:
    name: "{{item}}"
    state: present
  with_items:
        - "jenkins-{{jenkins_version}}"
        - git
        - java-1.8.0

- name: Assigning shell to jenkins user
  user:
    name: jenkins
    shell: /bin/bash

- name: Copying Jenkins Skell file in jenkins users home dir
  shell: "cp /etc/skel/.bash* /var/lib/jenkins"

- file:
    path: "{{ jenkins_home }}/.ssh"
    mode: 0700
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory

- file:
    path: "{{ jenkins_home }}/plugins"
    mode: 0755
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory

- name: Add user Public Key
  copy: 
     src: "../jenkins_master/files/jenkins_id_rsa.pub"
     dest: "{{ jenkins_home }}/.ssh/id_rsa.pub"
     mode: 0644
     owner: "{{ username }}"
     group: "{{ username }}"

- name: Add user Private Key
  copy: 
     src: "../jenkins_master/files/jenkins_id_rsa"
     dest: "{{ jenkins_home }}/.ssh/id_rsa"
     mode: 0600
     owner: "{{ username }}"
     group: "{{ username }}"

- name: Adding Bitbucket Public Key
  copy: 
     src: "../jenkins_master/files/bitbucket_pub"
     dest: "{{ jenkins_home }}/.ssh/known_hosts"
     mode: 0644
     owner: "{{ username }}"
     group: "{{ username }}"


- name: Pull Jenkins Configuration from bitbuket
  git:
    repo: "{{ jenkins_bucket_url }}"
    dest: "{{ jenkins_bucket }}"
    accept_hostkey: yes
    #clone: no
    force: yes
  become: yes
  become_user: "{{ username }}"

- name: Pull jenkins plugins from bitbuket
  git:
    repo: "{{ jenkins_plugin_bucket_url }}"
    dest: "{{ jenkins_plugin_bucket }}"
    accept_hostkey: yes
    force: yes
  become: yes
  become_user: "{{ username }}"


### // Add plugin name here my_var.yml to install on jenkins // ###
- name: Get other plugins from net
  get_url: 
   url: "https://updates.jenkins-ci.org/latest/{{item}}"
   dest: "{{  jenkins_home }}/plugins"
  with_items: "{{ jenkins_plugins }}"
  become: yes
  become_user: "{{ username }}"

- name: git config user name
  shell: git config --global user.name "{{ git_name }}" executable=/bin/bash
  become: yes
  become_user: "{{ username }}"

- name: git config user email
  shell: git config --global user.email "{{ git_email }}" executable=/bin/bash
  become: yes
  become_user: "{{ username }}"

- name: copying jobs and plugin from repo to jenkins home
  shell: "cp -fvr {{ jenkins_plugin_bucket }}/jenkins-plug/* {{  jenkins_home }}/plugins; cp -frv {{ jenkins_bucket }}/* /var/lib/jenkins/ ; chown  jenkins.jenkins -R /var/lib/jenkins/"
  #shell: "cp -frv {{ jenkins_bucket }}/* /var/lib/jenkins/ ; chown  jenkins.jenkins -R /var/lib/jenkins/"

- name: Start and Enabled jenkins Master Service
  service:
    name: jenkins
    #state: started
    enabled: yes

