jenkins_home: /var/lib/jenkins
jenkins_url: "http://127.0.0.1"
jenkins_port: "8080"

jenkins_java_opts: "-Djenkins.install.runSetupWizard=false"


jenkins_plugins:
        - ace-editor.hpi
        - amazon-ecr.hpi
        - amazon-ecs.hpi
        - analysis-collector.hpi
        - analysis-core.hpi
        - ansible.hpi
        - antisamy-markup-formatter.hpi
        - ant.hpi
        - artifactory.hpi
        - authentication-tokens.hpi
        - aws-credentials.hpi
        - aws-java-sdk.hpi
        - aws-lambda.hpi
        - bitbucket-build-status-notifier.hpi
        - bitbucket.hpi
        - bouncycastle-api.hpi
        - branch-api.hpi
        - build-metrics.hpi
        - build-timeout.hpi
        - build-token-root.hpi
        - checkmarx.hpi
        - checkstyle.hpi
        - chromedriver.hpi
        - cloudbees-folder.hpi
        - codefresh.hpi
        - codesonar.hpi
        - conditional-buildstep.hpi
        - config-file-provider.hpi
        - copyartifact.hpi
        - credentials-binding.hpi
        - credentials.hpi
        - crossbrowsertesting.hpi
        - cucumber-slack-notifier.hpi
        - cvs.hpi
        - description-setter.hpi
        - display-url-api.hpi
        - docker-build-publish.hpi
        - docker-build-step.hpi
        - docker-commons.hpi
        - docker-custom-build-environment.hpi
        - docker-plugin.hpi
        - docker-slaves.hpi
        - docker-traceability.hpi
        - docker-workflow.hpi
        - durable-task.hpi
        - ec2.hpi
        - email-ext.hpi
        - envinject.hpi
        - external-monitor-job.hpi
        - findbugs.hpi
        - git-client.hpi
        - github-api.hpi
        - github-branch-source.hpi
        - github.hpi
        - github-organization-folder.hpi
        - git.hpi
        - git-server.hpi
        - global-build-stats.hpi
        - gradle.hpi
        - handlebars.hpi
        - hipchat.hpi
        - htmlpublisher.hpi
        - icon-shim.hpi
        - ivy.hpi
        - jackson2-api.hpi
        - javadoc.hpi
        - JDK_Parameter_Plugin.hpi
        - jenkinsci-appspider-plugin.hpi
        - job-dsl.hpi
        - jquery-detached.hpi
        - jquery.hpi
        - junit.hpi
        - ldap.hpi
        - mailer.hpi
        - mapdb-api.hpi
        - matrix-auth.hpi
        - matrix-project.hpi
        - maven-invoker-plugin.hpi
        - maven-plugin.hpi
        - mercurial.hpi
        - momentjs.hpi
        - multiple-scms.hpi
        - nexus-artifact-uploader.hpi
        - node-iterator-api.hpi
        - pam-auth.hpi
        - parameterized-trigger.hpi
        - pipeline-build-step.hpi
        - pipeline-github-lib.hpi
        - pipeline-graph-analysis.hpi
        - pipeline-input-step.hpi
        - pipeline-milestone-step.hpi
        - pipeline-model-api.hpi
        - pipeline-model-definition.hpi
        - pipeline-model-extensions.hpi
        - pipeline-rest-api.hpi
        - pipeline-stage-step.hpi
        - pipeline-stage-tags-metadata.hpi
        - pipeline-stage-view.hpi
        - plain-credentials.hpi
        - pollscm.hpi
        - resource-disposer.hpi
        - role-strategy.hpi
        - run-condition.hpi
        - sauce-ondemand.hpi
        - scalable-amazon-ecs.hpi
        - scm-api.hpi
        - scm-sync-configuration.hpi
        - script-security.hpi
        - seed.hpi
        - selenium-builder.hpi
        - sonar.hpi
        - ssh-credentials.hpi
        - ssh-slaves.hpi
        - structs.hpi
        - subversion.hpi
        - timestamper.hpi
        - token-macro.hpi
        - windows-slaves.hpi
        - workflow-aggregator.hpi
        - workflow-api.hpi
        - workflow-basic-steps.hpi
        - workflow-cps-global-lib.hpi
        - workflow-cps.hpi
        - workflow-durable-task-step.hpi
        - workflow-job.hpi
        - workflow-multibranch.hpi
        - workflow-scm-step.hpi
        - workflow-step-api.hpi
        - workflow-support.hpi
        - ws-cleanup.hpi

