- include_vars: ../jenkins_master/defaults/my_var.yml

## Configure Jenkins master

- name: Start and Enabled jenkins Master Service
  service:
    name: jenkins
    state: stopped

#- debug: msg="{{item}}"
#  with_items: "{{ jenkins_plugins }}"

#- name: Get all plugins
#  get_url: 
#   url: "https://updates.jenkins-ci.org/latest/{{item}}"
#   dest: "{{  jenkins_home }}/plugins"
#  with_items: "{{ jenkins_plugins }}"
#  with_items:
#        - sonar.hpi
#        - emailext-template.hpi

- name: Assigning shell to jenkins user
  user:
    name: jenkins
    shell: /bin/bash

- file:
    path: "{{ jenkins_home }}/.ssh"
    mode: 0700
    owner: jenkins
    group: jenkins
    state: directory

- name: Add user Public Key
  #remote_user: jenkins
  copy: 
     src: "../jenkins_master/files/id_rsa.pub"
     dest: "{{ jenkins_home }}/.ssh/id_rsa.pub"
     #dest: "/root/.ssh/id_rsa.pub"
     mode: 0644
     owner: jenkins
     group: jenkins

- name: Add user Private Key
  #remote_user: jenkins
  copy: 
     src: "../jenkins_master/files/id_rsa"
     #dest: "/root/.ssh/id_rsa"
     dest: "{{ jenkins_home }}/.ssh/id_rsa"
     mode: 0600
     owner: jenkins
     group: jenkins

- name: Start and Enabled jenkins Master Service
  service:
    name: jenkins
    state: started
    enabled: yes

